package panel;

import difamserv.celdaRander;
import difamserv.frmPrincipal;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

public class miListaComprasEstado extends javax.swing.JPanel {

    public miListaComprasEstado() {
        initComponents();
        Vector  columnas = new Vector();
        columnas.add("ID COMPRA");
        columnas.add("PROVEEDOR");
        columnas.add("MONTO PAGADO");
        columnas.add("MONTO TOTAL");
        columnas.add("FECHA COMPRA");
        columnas.add("ESTADO");
        Vector datos = frmPrincipal.miConex.consDatosParaTablas("idCompra,"
                + "nombreprov,"
                + "if((select sum(montopagoC) from compra C inner join pagocompra using(idcompra) where C.idCompra=compra.idCompra) IS NULL,0.00,(select sum(montopagoC) from compra C inner join pagocompra using(idcompra) where C.idCompra=compra.idCompra)) as pago,"
                + "montoTotalC,"
                + "fechaCompra,"
                + "if(estadoCompra=0,'ABIERTO','CERRADO') as estado",
                "compra",
                "inner join proveedor using(idProveedor)");
        if(!datos.isEmpty()){
            tabla.setDefaultRenderer(Object.class, new celdaRander(-1));
            tabla.setRowHeight(20);
            tabla.setModel(new DefaultTableModel(datos,columnas));
            frmPrincipal.packColumn(tabla, -1, 2);
        }
        //select idCompra,nombreprov,if((select sum(montopagoC) from compra inner join pagocompra using(idcompra) where idCompra=compra.idCompra) IS NULL,0.00,(select sum(montopagoC) from compra inner join pagocompra using(idcompra) where idCompra=compra.idCompra)) as pago,montoTotalC,fechaCompra,if(estadoCompra=0,'ABIERTO','CERRADO') as estado from compra inner join proveedor using(idProveedor);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        sc = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPagos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("<html><body>\nNOTA: Si una  compra no ha sido cerrada, los pagos  no podrán registrarse. El monto final se observará cuando cierre la compra.\n<br>\n</body></html>");
        jLabel3.setMaximumSize(new java.awt.Dimension(617, 20));
        jLabel3.setMinimumSize(new java.awt.Dimension(617, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(617, 20));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        sc.setViewportView(tabla);

        tablaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPagos);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Pagos >>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(68, 600));
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("<< Compras");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setMaximumSize(new java.awt.Dimension(53, 600));
        jLabel2.setMinimumSize(new java.awt.Dimension(53, 40));
        jLabel2.setOpaque(true);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 67, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(434, 434, 434))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        Vector  columnas = new Vector();
        columnas.add("ID PAGO");
        columnas.add("MONTO PAGO");
        columnas.add("FECHA PAGO");
        tablaPagos.setModel(new DefaultTableModel(null,columnas));
        Vector datos = frmPrincipal.miConex.consDatosParaTablas("idPagoC,"
                + "montoPagoC,"
                + "fechaPagoC",
                "pagocompra",
                "where idCompra='"+tabla.getValueAt(tabla.getSelectedRow(), 0)+"'");
        if(!datos.isEmpty()){
            tablaPagos.setDefaultRenderer(Object.class, new celdaRander(-1));
            tablaPagos.setRowHeight(20);
            tablaPagos.setModel(new DefaultTableModel(datos,columnas));
            frmPrincipal.packColumn(tablaPagos, -1, 2);
        }
    }//GEN-LAST:event_tablaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane sc;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablaPagos;
    // End of variables declaration//GEN-END:variables

}
