/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * panelPagoEmpleados.java
 *
 * Created on 28/09/2014, 09:25:58 AM
 */
package panel;

import dialog.vizProd;
import difamserv.celdaRander;
import difamserv.frmPrincipal;
import java.awt.BorderLayout;
import java.awt.event.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dany
 */
public class panelPagoEmpleados extends javax.swing.JPanel {

    Vector columnas;

    /** Creates new form panelPagoEmpleados */
    public panelPagoEmpleados() {
        initComponents();
        columnas = new Vector();
        columnas.add("Venta");
        columnas.add("Nombre Cliente");
        columnas.add("Monto Total");
        columnas.add("Fecha Venta");
        columnas.add("Fecha Limite");
        columnas.add("Fecha Cubierta");
        columnas.add("Dias Diferencia");
        columnas.add("LEY APLICADA");
        columnas.add("Ganancia");
        columnas.add("Pago por Venta");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtAM = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtAP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVentaC = new javax.swing.JButton();
        btnVentaP = new javax.swing.JButton();
        txtT = new javax.swing.JTextField();
        txtFN = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMPerm = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        lblTotal = new javax.swing.JTextField();
        txtID2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

        txtAM.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtAM.setEnabled(false);
        txtAM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAMKeyReleased(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtNombre.setEnabled(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        txtAP.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtAP.setEnabled(false);
        txtAP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAPKeyReleased(evt);
            }
        });

        jLabel6.setText("Teléfono:");

        jLabel2.setText("Apellido Paterno:");

        txtD.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtD.setEnabled(false);
        txtD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDKeyReleased(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel4.setText("Fecha de Nacimiento:");

        jLabel3.setText("Apellido Materno:");

        jLabel5.setText("Dirección:");

        btnVentaC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sube.gif"))); // NOI18N
        btnVentaC.setText("VENTAS CERRADAS");
        btnVentaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaCActionPerformed(evt);
            }
        });

        btnVentaP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete16.png"))); // NOI18N
        btnVentaP.setText("VENTAS PENDIENTES");
        btnVentaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaPActionPerformed(evt);
            }
        });

        txtT.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtT.setEnabled(false);
        txtT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTKeyReleased(evt);
            }
        });

        txtFN.setToolTipText("DD/MM/AAAA");
        txtFN.setEnabled(false);
        txtFN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFNKeyReleased(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));

        lblFoto.setBackground(new java.awt.Color(255, 255, 255));
        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prer.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setText("Monto de Crédito Permitido:");

        txtMPerm.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtMPerm.setEnabled(false);
        txtMPerm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMPermKeyReleased(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        txtEmail.setEnabled(false);
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        jLabel9.setText("Email:");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });

        jLabel10.setText("ID Agente:");

        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/precio.png"))); // NOI18N
        btnPagar.setText("PAGAR A EMPLEADO");
        btnPagar.setEnabled(false);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtD, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMPerm)
                                    .addComponent(jLabel7)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtFN, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtT, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtAM, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(btnVentaC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVentaP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPagar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMPerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPagar)
                            .addComponent(btnVentaP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVentaC)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel8.setText("Lista de Remisiones cerradas y pendientes, para realizar pago al empleado, selecciona el botón VENTAS CERRADAS:");

        tabla.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Venta", "Cliente Expedido", "Monto de Venta", "Fecha Venta", "Fecha Cerrada", "Días transcurridos", "Ley Aplicada", "Ganancia", "Pago Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        lblTotal.setFont(new java.awt.Font("Lao UI", 1, 15)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lblTotal.setText("0.00");
        lblTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total de Pago:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lao UI", 0, 12))); // NOI18N
        lblTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblTotalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblTotalKeyTyped(evt);
            }
        });

        txtID2.setFont(new java.awt.Font("Lao UI", 1, 15)); // NOI18N
        txtID2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtID2.setText("0.00");
        txtID2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de Pago:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lao UI", 0, 12))); // NOI18N
        txtID2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtID2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtID2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID2, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        StringBuilder ventas=new StringBuilder("");
        for (int i = 0; i < tabla.getRowCount(); i++) {
            frmPrincipal.miConex.actualizaRegistro("venta", "estadoCobro='1'", "idVenta='" + tabla.getValueAt(i, 0) + "'");
            ventas.append(tabla.getValueAt(i, 0));
            if(!(i == tabla.getRowCount()-1)){
                ventas.append(",");
            }
            System.out.println("Ventas:"+ventas);
        }
        frmPrincipal.miConex.altaRegistro("pagoEmpleado", "null,"+lblTotal.getText()+",'"+ventas+"',sysdate(),"+txtID.getText());
        HashMap param = new HashMap();
        System.out.println("IDPAGO EMPLEADO: " + frmPrincipal.miConex.ConsultaDato("idPagoE", "pagoEmpleado", " where fechaCobro=sysdate() and idEmpleado='"+txtID.getText()+"'"));
        param.put("idEmp",txtID.getText().toString());//frmPrincipal.miConex.ConsultaDato("idPagoE", "pagoEmpleado", " where fechaCobro=sysdate() and idEmpleado='"+txtID.getText()+"'"));
        param.put("ventas",ventas.toString());
        frmPrincipal.agregaPanel(new panelVistaReportes("pagare",param), new BorderLayout(), null, null);
    }//GEN-LAST:event_btnPagarActionPerformed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_txtEmailKeyReleased

    private void txtMPermKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMPermKeyReleased
        // TODO add your handling code here:
}//GEN-LAST:event_txtMPermKeyReleased

    private void txtFNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFNKeyReleased
        //validaEnter(evt, txtT);
}//GEN-LAST:event_txtFNKeyReleased

    private void txtTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTKeyReleased
        //validaEnter(evt, txtD);
}//GEN-LAST:event_txtTKeyReleased

    private void btnVentaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaPActionPerformed
        btnPagar.setEnabled(false);
        consulta("estadoVenta='0' and");
        //ControlBotones(false, true);
}//GEN-LAST:event_btnVentaPActionPerformed

    private void btnVentaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaCActionPerformed
        btnPagar.setEnabled(true);
        consulta("estadoVenta='1' and");
        /*ControlBotones(true, false);
        txtNombre.requestFocus(true);
        AoC = true;*/
}//GEN-LAST:event_btnVentaCActionPerformed

    private void txtDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDKeyReleased
        /*if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        btnGuardarActionPerformed(null);
        }*/
}//GEN-LAST:event_txtDKeyReleased

    private void txtAPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAPKeyReleased
        //validaEnter(evt, txtAM);
}//GEN-LAST:event_txtAPKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        //validaEnter(evt, txtAP);
}//GEN-LAST:event_txtNombreKeyReleased

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtNombreActionPerformed

    private void txtAMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAMKeyReleased
        //validaEnter(evt, txtFN);
}//GEN-LAST:event_txtAMKeyReleased

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            llenarCuadros();
            txtID.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            new vizProd(null, true, txtID, 5, 0);
        }

    }//GEN-LAST:event_txtIDKeyReleased

    private void lblTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblTotalKeyReleased
        /*if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            llenarCuadros();
            txtIDP.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_F2) {
            new vizProd(null, true, txtID, 2, 0);
        }*/
}//GEN-LAST:event_lblTotalKeyReleased

    private void lblTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblTotalKeyTyped
        /*if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            llenarCuadros();
            txtIDP.requestFocus();
        }*/
}//GEN-LAST:event_lblTotalKeyTyped

    private void txtID2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtID2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID2KeyReleased

    private void txtID2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtID2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID2KeyTyped

    /*    public void llenarTabla(String condicion) {
    tabla.setDefaultRenderer(Object.class, new celdaRander(-1));
    tabla.setRowHeight(25);
    tabla.setModel(new DefaultTableModel(frmPrincipal.miConex.consDatosParaTablas("idCliente,razonSocialCliente,nombreCli,fechaNac,limiteMontoCred,limiteDiasCred,dias,horario,descRuta,nombreEmp,tipoCliente,dcalleCli,dnoInt,dnoExt,coloniaCli,estadoCli,poblacionCli,cP ,telLCli,telCCli,email,fax,curp,descuentoC,cuentaBanco,rfcCliente,credito,contado,factura,remision,fechaRegistro,contacto,observaciones,IF(estadoCliente='1','ACTIVO','INACTIVO')", "cliente", "inner join ruta_agente using(idR_A) inner join ruta using(idRuta)inner join empleado using(idEmpleado) WHERE nombreCli like '%" + txtBuscar.getText().toUpperCase() + "%' " + condicion), columnas));
    tabla.setAutoCreateRowSorter(true);
    frmPrincipal.packColumn(tabla, 0, 2);
    }
     */
    public void llenarCuadros() {
        Vector datosCli = frmPrincipal.miConex.consDatosParaCampos("nombreemp,apellidopatemp,apellidopatemp,fechaNacC,direccionEmp,telefonoEmp,emailEmp,montoVentaPerm", "empleado", " where idEmpleado='" + txtID.getText() + "'");
        if (!datosCli.isEmpty()) {
            tabla.setDefaultRenderer(Object.class, new celdaRander(-1));
            tabla.setRowHeight(25);

            datosCli = (Vector) datosCli.get(0);
            txtNombre.setText(datosCli.get(0).toString());
            txtAP.setText(datosCli.get(1).toString());
            txtAM.setText(datosCli.get(2).toString());
            txtFN.setText(datosCli.get(3).toString());
            txtD.setText(datosCli.get(4).toString());
            txtT.setText(datosCli.get(5).toString());
            txtEmail.setText(datosCli.get(6).toString());
            txtMPerm.setText(datosCli.get(7).toString());

            consulta("");

            //lblFVen.setText(sumarDias(lblFEmi.getText(), Integer.parseInt(datosCli.get(8).toString())).toString());
            //frmPrincipal.cargaImagen("foto", "cliente", "where idCliente='" + txtID.getText() + "'", lblFoto, 128, 128, defaultIcon);
            //txtID.setText("");
        }
        btnPagar.setEnabled(false);
    }

    public void calculaPoliticas() {
        double ganancia=0.00;
        if (tabla.getRowCount()>0) {
            for (int i = 0; i < tabla.getRowCount(); i++) {
                int diasDif = Integer.parseInt(tabla.getValueAt(i, 6).toString());
                ganancia = Double.parseDouble(tabla.getValueAt(i, 8).toString());
                System.out.printf("Dias:%s Ganancia:%s",diasDif,ganancia);
                if(diasDif<=15){
                    ganancia = ganancia;
                }else if(diasDif<=22){
                    ganancia = ganancia*0.70;
                }else if(diasDif<=30){
                    ganancia = ganancia*0.50;
                }else if(diasDif<=45){
                    ganancia = ganancia*0.30;
                }else if(diasDif<=60){
                    ganancia = ganancia*0.10;
                }else{
                    ganancia = 0;
                    //frmPrincipal.miConex.actualizaRegistro("venta","IF(cliOAgente=0,cliOAgen=1,'')","idVenta='"+tabla.getValueAt(i, 0).toString()+"'");
                    //Aqui pasar la cuenta diferencial como pago del agente
                }
                tabla.setValueAt(ganancia,i, 9);
            }
        }
        CalculaTotal(9);
    }

    public void CalculaTotal(int col){
        double pagoVenta = 0.00;
        for (int i = 0; i < tabla.getRowCount(); i++) {
            pagoVenta += Double.parseDouble(tabla.getValueAt(i, col).toString());            
        }
        lblTotal.setText(""+pagoVenta);
    }
    public void consulta(String condicion) {
        Vector datos = frmPrincipal.miConex.consDatosParaTablas("V.idVenta,C.razonsocialcliente,V.montoTotalV,V.fechaVenta,ADDDATE(V.fechaVenta,C.limitediascred) as fechaVence,fechaCierre,DATEDIFF(curdate(),ADDDATE(V.fechaVenta,C.limitediascred)) as dias,DATEDIFF('2014-09-29',ADDDATE(V.fechaVenta,C.limitediascred)) as dias1,V.gananciaVEmp", "venta", "V inner join cliente C inner join ruta_agente RA inner join empleado E inner join ruta R ON C.idCliente=V.idCliente and C.idR_A=RA.idR_A and RA.idEmpleado=E.idEmpleado and R.idruta=RA.idruta where " + condicion + " estadoCobro='0' and E.idEmpleado='" + txtID.getText() + "'");
        if (datos.size() > 0) {
            tabla.setModel(new DefaultTableModel(datos, columnas));
            tabla.setAutoCreateRowSorter(true);
            frmPrincipal.packColumn(tabla, 0, 2);

        } else {
            tabla.setModel(new DefaultTableModel(null, columnas));
        }
        calculaPoliticas();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnVentaC;
    private javax.swing.JButton btnVentaP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoto;
    public javax.swing.JTextField lblTotal;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtAM;
    private javax.swing.JTextField txtAP;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtFN;
    private javax.swing.JTextField txtID;
    public javax.swing.JTextField txtID2;
    private javax.swing.JTextField txtMPerm;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtT;
    // End of variables declaration//GEN-END:variables
}
